### ISSUE TITLE
RNCookieManagerIOS. was called with 2 arguments but expects 1 arguments.

### ISSUE THREAD

**Issue by williams-voon** [joeferraro/react-native-cookies#69] opened 2017-08-10 06:31 UTC
I used RN 0.44 before, the react-native-cookies works.
Now I update RN to 0.47, and got the following error:

```
RNCookieManagerIOS. was called with 2 arguments but expects 1 arguments.
If you haven't changed this method your self, this usually means that your version of the native code and JavaScript code are out of sync. Updating both should make this error go away.
```

On Android platform, I got this error:
```
RNCookieManagerAndroid.get got 4 arguments, expected 3.
```

My code:
CookieManager.get(this.config.urlPrefix, (err, res) => {

Help is wanted.

**Comment by joeferraro** [comment] 2017-08-10 11:42
Duplicate of #68

**Closed by joeferraro** 2017-08-10 11:42 UTC

**Comment by williams-voon** [comment] 2017-08-10 14:32
I changed my code to solve the problem:

CookieManager.get(this.config.urlPrefix).then( (res) => {})
